# Generated by Django 2.1.5 on 2019-01-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='error_code',
            field=models.PositiveIntegerField(default=0, verbose_name='Код ответа'),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='http_method',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Нttp метод'),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='ip_addr',
            field=models.GenericIPAddressField(db_index=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='response_size',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Размер ответа'),
        ),
    ]
