version: '3.0'

services:
  db:
    image: postgres:11.1-alpine
    container_name: lp_db
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - ./.env
    ports:
      - 5432:5432

  redis:
    image: redis:5.0-alpine
    container_name: lp_redis
    env_file:
      - ./.env
    ports:
      - 6379:6379
